### PR TITLE
Add extensions via function in `upgrade.R`

### LINKED ISSUE #274: support/configuration for SQLite3's `generate_series`
What would it take so enable/support/configure RSQLite to allow using `generate_series` (see [The generate\_series Table\-Valued Function](https://www.sqlite.org/series.html)) 

Trying after `remotes::install_github("r-dbi/RSQLite#273")` results as follows:
 
```
dbExecute(db,'SELECT value FROM generate_series(5,100,5)')
Error in result_create(conn@ptr, statement) : 
  no such table: generate_series
In addition: Warning message:
Closing open result set, pending rows 
```

It was suggested to me that requesting this is the key to:  [enabling SQLite's generate\_sequence to be used in R's sqldf library under MS windows](https://stackoverflow.com/questions/53568665/enabling-sqlites-generate-sequence-to-be-used-in-rs-sqldf-library-under-ms-win)

Presumably an approach is similar to https://github.com/r-dbi/RSQLite/pull/266 only with [this source](https://www.sqlite.org/src/artifact/0c97f63378fddc9f)...???

### PR DESCRIPTION
**Pull request by mgirlich**
Fixes #274.

* I'm not sure whether we also need patch files for every extension
* The current naming for loading extensions is in my opinion a bit confusing. `initExtension()` to load the math functions and `initRegExp()` to load the regular expressions. I think it would be nice to always have "extension" somewhere in the name.
* I didn't manage to compile the ICU extension. It always complained "'unicode/utypes.h' file not found" even though I installed `icu4c` with homebrew... (also see [stackoverflow](https://stackoverflow.com/questions/33259191/installing-libicu-dev-on-mac))

``` r
db <- RSQLite::datasetsDb()
RSQLite::initSeries(db)
RSQLite::dbGetQuery(db, "SELECT value FROM generate_series(5,20,5);")
#>   value
#> 1     5
#> 2    10
#> 3    15
#> 4    20
```

<sup>Created on 2021-11-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks for working on this! I think we can soft-deprecate `initExtension()` in favor of something clearer.

sqlite is plain C, do we need to compile differently with extensions that are C++?

**Review by krlmlr — COMMENTED** [review]
Another thing: should extensions live in `src/vendor/extensions`, with different compilation rules?

**Comment by mgirlich** [comment]
I put the extensions in their own folder `src/vendor/extensions` as suggested. They now have their own compilation rules in `MAKEVARS`. I don't know much about make files so you might have some improvement suggestions.
Currently, the `MAKEVARS` file is changed by hand for every extension but this could also be automated.

* I am not sure what the `regexp.patch` file is for. Do we also need to patch the other extension files?
* Should we compile the extensions as shared library? At least that's what it says on https://www.sqlite.org/loadext.html? I don't know what the pros and cons would be.

**Comment by krlmlr** [comment]
Thanks for working on this. What are the compilation failures in the CSV extension about? Should we remove it for now and investigate separately?

**Comment by krlmlr** [comment]
I tweaked a bit. It's weird that compilation of the csv extension works on some systems, is it relying on system header files? That would be undesirable, we're vendoring everything.

Let's avoid the extra complexity of static libraries.

**Comment by krlmlr** [comment]
Added an explicit include path, let's see if the build behaves now.

Instead of multiple `initXXX()` functions, should we keep only `initExtensions()` and add a `name` argument? The default extension would be `"math"`, the others would be called by their short name. I don't m

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
