### PR TITLE
Replace Rcpp by cpp11

### PR DESCRIPTION
**Pull request by mgirlich**
I think it might be worth switching from `Rcpp` to `cpp11`. See [Motivations for cpp11](https://cpp11.r-lib.org/articles/motivations.html) for some reasons.
Compilation is now much faster (~28s vs ~52s) and I think it is mostly easier to work with `cpp11`.

To Do
* [ ] `busy_callback_helper()` -> how to catch eval error and interrupt?
* [ ] `result_release()` -> make this work with `cpp11::external_pointer`
* [ ] find replacement for `Rcpp::warningcall(R_NilValue, std::string("Ignoring remaining part of query: ") + tail);`
* [ ] figure out why `cpp11::warning()` crashes
* [ ] adapt `astyle()`
* [ ] `get_column_info()` can probably directly use `cpp11::dataframe`
* [ ] maybe remove some `STRICT_R_HEADERS` and `R_NO_REMAP`

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks! Compilation on gcc fails, could you please take a look?

**Comment by mgirlich** [comment]
I could not reproduce it locally so I just hope this works.

**Comment by krlmlr** [comment]
Thanks, appreciated.

`on.exit(after = )` requires recent-ish R, we can use `withr::defer()` instead to fix the oldrel-4 failures.

I've added a test for the interrupt behavior to https://github.com/r-dbi/RSQLite/pull/401. Is this problem solvable, do we need a change to cpp11? Are there any downsides to vendoring the cpp11 package?

`pch.h` helps speed up building locally, through precompiled headers. It's important that this is the first preprocessor statement in each module. You can edit this file instead of making the changes in all files. (I need to remember how this is used, though.)

I don't fully understand the other check items yet.

**Comment by krlmlr** [comment]
I'll finish this, thanks!

**Pull request merged**
